### ISSUE TITLE
blank page at start

### ISSUE THREAD

**Issue by hamoha31** [in-dex/ionic2-foodApp#1]
Hi, 
I am trying to learn ionic2 and I found your amazing app. I am trying to run it on my PC and Mac. Both of them give me blank screen and nothing is on.
I am running last ionic2 release .

**Comment by b-coimbra** [comment]
You have to do the following command `npm install` to install all the dependencies needed to run the app.
I'm still working on it, and a lot hasn't been done yet, anyway glad you like it.

**Comment by hamoha31** [comment]
Yes I see, I did it then I closed the issue.

It is amazing project, I learned a lot.
I like the way how you customize the things.
