### ISSUE TITLE
Cannot find module '../validators/CustomValidators'

### ISSUE THREAD

**Issue by fxcosta** [in-dex/ionic2-foodApp#2]
Hello! This project is amazing for those wanting to learn more about Ionic2. Thanks you for the project !! I'm trying to run on my machine but I am getting the following error in building by ionic serve:

Cannot find module '../validators/CustomValidators' from '/var/www/ionic2-foodApp/app/pages/login'

How can I fix this problem without changing the login? Thank you!

**Comment by b-coimbra** [comment]
Hey! Thanks for submitting the issue.
Can you please tell me which version of ionic you currently have?

**Comment by fxcosta** [comment]
i have 2.0.0-beta.35 version

**Comment by b-coimbra** [comment]
I have tested the app on another computer, and it works perfectly (with ionic 2.0.0-beta.37). 
I don't really know how to fix this problem right now, but maybe you should try to update both Cordova and Ionic. In case I find a sollution, I'll let you know.

Maybe you should take a look at another cool project for learning: 
[ionic conference app](https://github.com/driftyco/ionic-conference-app)

**Comment by b-coimbra** [comment]
I'll be closing the issue.
But it probably has to do with the structure of the modules that always keep changing. (Check the [Change Log](https://github.com/driftyco/ionic/blob/master/CHANGELOG.mdl))
This is all I can do for you, thanks again.
